sudo: required
language: php
dist: trusty

php:
  - 7.1

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - libmysqlclient-dev
      - libmysqlclient20
      - mysql-community-client
      - mysql-common
      - mysql-community-server
  chrome: stable

before_script:
  - cp .env.travis .env
  - travis_retry composer install --no-interaction
  - mysql -e 'CREATE DATABASE openhelpdesk_test;'
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan key:generate
  - php artisan serve > /dev/null 2>&1 &

script:
  - php artisan dusk